# Generated by Django 4.2.4 on 2023-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_product",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
